from setuptools import setup, find_packages

setup(
    name='MessengerBot',
    version='0.1.0',  
    description='CheackReadMe',
    long_description=open('README.md').read(),
    author='Black',
    author_email='storting124@mail.ru',
    packages=find_packages(),
    package_dir={"": "src"},
    install_requires=[
        "attrs==25.3.0",
        "beautifulsoup4==4.13.5",
        "cachetools==5.5.2",
        "certifi==2025.8.3",
        "cffi==1.17.1",
        "charset-normalizer==3.4.3",
        "DAWG2-Python==0.9.0",
        "google==3.0.0",
        "google-api-core==2.25.1",
        "google-api-python-client==2.181.0",
        "google-auth==2.40.3",
        "google-auth-httplib2==0.2.0",
        "google-auth-oauthlib==1.2.2",
        "google-pasta==0.2.0",
        "googleAPI==0.1.0",
        "googleapis-common-protos==1.70.0",
        "h11==0.16.0",
        "httplib2==0.30.0",
        "idna==3.10",
        "oauth2client==4.1.3",
        "oauthlib==3.3.1",
        "outcome==1.3.0.post0",
        "packaging==25.0",
        "proto-plus==1.26.1",
        "protobuf==6.32.0",
        "pyasn1==0.6.1",
        "pyasn1_modules==0.4.2",
        "pycparser==2.22",
        "pymorphy3==2.0.4",
        "pymorphy3-dicts-ru==2.4.417150.4580142",
        "pyparsing==3.2.3",
        "pyperclip==1.9.0",
        "PySocks==1.7.1",
        "python-dotenv==1.1.1",
        "requests==2.32.5",
        "requests-oauthlib==2.0.0",
        "rsa==4.9.1",
        "rus-gender-detection==1.0.0",
        "selenium==4.35.0",
        "setuptools==80.9.0",
        "six==1.17.0",
        "sniffio==1.3.1",
        "sortedcontainers==2.4.0",
        "soupsieve==2.8",
        "trio==0.30.0",
        "trio-websocket==0.12.2",
        "typing_extensions==4.14.1",
        "uritemplate==4.2.0",
        "urllib3==2.5.0",
        "webdriver-manager==4.0.2",
        "websocket-client==1.8.0",
        "wsproto==1.2.0"

    ],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
    ]
)